### PR TITLE
Test toc generation bot

### PR DESCRIPTION
**Pull request by expipiplus1**

### CODE REVIEW

**Comment by expipiplus1** [comment]
> Wow. What are you cooking up here? I am gonna call you bot-maker from now one. ;-)

I noticed a few times that the table of contents got out of date, so we should check it in CI, but it was also a pain to regenerate, so why not have the bot do it

**Comment by expipiplus1** [comment]
ok, all working :partying_face:

**Comment by jkwak-work** [comment]
Is `/regenerate-toc` working now?
I think I need to update the CONTRIBUTING.md for these magic bot commands.

**Pull request closed without merging**
