### PR TITLE
Update spirv-tool to upstream/main branch

### PR DESCRIPTION
**Pull request by kaizhangNV**

### CODE REVIEW

**Comment by kaizhangNV** [comment]
I have to update the spirv-headers as well.

**Comment by csyonghe** [comment]
Seems like there are some issues with CMake process.

**Review by csyonghe — DISMISSED** [review]

**Comment by kaizhangNV** [comment]
> Seems like there are some issues with CMake process.

yea, two issues.
One is head is not update to date, another one is the cmake. Not sure if they are related yet. I updated the headers just now.

**Comment by kaizhangNV** [comment]
thanks for approval, I will merge it when all CIs pass.

**Comment by csyonghe** [comment]
Trivial changes like this don't need an approval. Feel free to merge as long as CI passes.

**Pull request merged**
