### PR TITLE
Dont require llvm for building generators

### PR DESCRIPTION
**Pull request by expipiplus1**

### CODE REVIEW

**Comment by csyonghe** [comment]
@expipiplus1 can you post here once you are able to confirm a test release can be created with this PR?

**Comment by expipiplus1** [comment]
> @expipiplus1 can you post here once you are able to confirm a test release can be created with this PR?

looks good, macos doesn't try to download llvm any more
https://github.com/shader-slang/slang/actions/runs/10484700990/job/29039485323

**Review by csyonghe — APPROVED** [review]

**Comment by csyonghe** [comment]
Looks good, thank you!

Will we still have that racing condition where if some build process creates a release first then we can fail?

**Comment by expipiplus1** [comment]
nope, because it shouldn't try to download anything at all. But in the unlikely event that it happens on a user machine (them building from a release before all the assets are populated) they'll now get a much more sensible error message.

**Pull request merged**
