### PR TITLE
Implement semantics for WGSL

### PR DESCRIPTION
**Pull request by aleino-nv**
This helps to address issue #4943.

### CODE REVIEW

**Comment by jkwak-work** [comment]
Shouldn't we add some test cases or enable existing tests for this change?

**Comment by csyonghe** [comment]
Yes, we should. I don't consider this PR to close any specific issue due to lack of tests, but I would rather have this merged in instead of having no support at all.

**Comment by aleino-nv** [comment]
This change itself doesn't close the issue as mentioned in the change description.
As mentioned in the linked issue title, the issue is indeed about enabling GFX tests.
Before closing the issue, I will enable all tests that should be passing.

**Pull request merged**
