### PR TITLE
Metal compute tests

### PR DESCRIPTION
**Pull request by skallweitNV**
This PR adds support for running compute tests with the new metal backend.

The current state is:
- 280 tests pass
- 18 tests fail (generate unexpected result)
- 155 tests fail to compile (in the metal downstream compiler)

All tests that fail to compile are disabled using
```
//DISABLE_TEST(compute):COMPARE_COMPUTE:-slang -shaderobj -mtl
```

See #4291 for more details.

### CODE REVIEW

**Comment by skallweitNV** [comment]
I don't quite understand why this change leads to the following failing tests:

- tests/compute/matrix-layout-structured-buffer.slang.3 syn (dx12)
- tests/compute/matrix-layout-structured-buffer.slang.4 syn (dx12)
- tests/compute/buffer-layout.slang.5 syn (cuda)

Also there is one `COMPARE_HLSL_RENDER` test that fails on metal:

- tests/bugs/texture2d-gather.hlsl

@csyonghe ?

**Comment by csyonghe** [comment]
The texture2d test may be using a vertex-fragment shader and we seem to be generating invalid vertex shader code for metal, causing the test to fail.

**Comment by csyonghe** [comment]
It sure about the matrix layout tests. None of the changes here seemed to be relevant.

**Comment by skallweitNV** [comment]
I "fixed" the tests by specifying the actual APIs they should run on instead of disabling for metal.

**Review by csyonghe — APPROVED** [review]

**Comment by csyonghe** [comment]
Looks good! We can clean up the test discovery logic later to make this more elegant, but we don't have to do that now.

**Pull request merged**
