### PR TITLE
Locate metal compiler using xcrun.

### PR DESCRIPTION
**Pull request by csyonghe**

### CODE REVIEW

**Comment by csyonghe** [comment]
This isn't working on the GitHub CI machine. I need to investigate locally on a Mac.

**Review by jkwak-work — APPROVED** [review]
Code looks good to me

**Comment by skallweitNV** [comment]
FYI, I had to use `macosx` as an SDK name to make this work on my machine.

**Comment by skallweitNV** [comment]
This code currently returns an invalid path containing a trailing newline. I opened #4285 to fix this.

**Comment by skallweitNV** [comment]
I added this change in #4287

**Comment by skallweitNV** [comment]
@csyonghe Please close this as its part of #4287

**Comment by csyonghe** [comment]
Subsumed by 4287.

**Pull request closed without merging**
