### PR TITLE
Separation of Binding/Resource construction on Renderer interface

### PR DESCRIPTION
**Pull request by jsmall-nvidia**
Previously the Renderer interface, would construct BindingState using information ShaderInputLayout. The resources constructed and the binding would then be hidden behind the opaque BindingState object. 

This PR completes the work to make the Renderer interface able to construct Resources and then using those resources and a BindingState::Desc create a binding state. 

Doing so makes the Renderer interface more flexible and also means that less code needs to be repeated within each Render implementation. It decouples the Renderer from the specifics of the render-test/ShaderInputLayout implementation. 

As part of this effort map/unmap was implemented for all Renderers, and a utility function used for serializing 'serializeBindingOutput' instead of requiring an implementation in each Renderer impl.

### CODE REVIEW

**Comment by tfoleyNV** [comment]
Is this ready for me to review? I see new commits coming in.

**Comment by jsmall-nvidia** [comment]
So RegisterList, RegisterSet, and RegisterDesc
Ok - probably means I need to have more comments in the code. The basic idea is

RegisterSet - defines a set of registers a particular binding might use. 
RegisterDesc - describes all of the registers for all the different shader binding styles (held as an array indexed via 'ShaderStyle')

RegisterSet is designed to be compact. Most bindings only need a single index, but some (in gl) might be a long list. The 'trick' is to use the numIndices to determine the scenario. If 0, well there aren't any. If 1, it uses the index held in RegisterSet, if > 1 then the index is actually a baseIndex into the m_indices array in BindingSet::Desc

Which is a little obtuse, but compact. In practice you might just want to iterate over a 'List' (or array), but you can't do that because RegisterSet doesn't necessarily hold all of the contents and so can't just write a begin/end method. A RegisterList - is just such a thing, and you can just construct it on the desc, from the register set, and then just iterate over it. If we had a Slice<T> type (an array without backing) then that would be better. 

It could be argued the naming could be a little more clear retrospectively too.

**Comment by tfoleyNV** [comment]
Two questions I have looking forward:

1. Does it actually make sense to use a single binding type for all buffers, or should buffers, UAVs, and SRV buffers be split into their own cases? I guess a similar question would arise for textures bound as UAVs.

2. The current binding data structures seem to be in the “push” direction: “take this resource and bind it over there!” I can imagine it would be more efficient (and maybe simpler) to have the renderer-level structures be turned around in the “pull” direction: “here is your root signature: for table zero, first bind this SRV, then that CBV, etc.”

Anyway, like I said I the review feedback, the changes in this PR are a prerequisite for anything I’m talking about here...

**Comment by jsmall-nvidia** [comment]
"Does it actually make sense to use a single binding type for all buffers, or should buffers, UAVs, and SRV buffers be split into their own cases? I guess a similar question would arise for textures bound as UAVs."

I'm not sure. Here I was aiming for the shortest path such that there wasn't a dependency. For the moment I think this binding interface is reasonable for the testing use case. For a 'proper' render it probably would not be. 

In terms of changing the API to be more 'pull' - perhaps what's appropriate may come out of supporting more fully other apis (say vulkan) and/or from trying to use reflection to drive binding. It remains somewhat odd to give the Renderer say binding indices for both hlsl, and glsl when it only needs one for example, and not entirely clear how that would extend nicely to say vulkan or other apis.

**Pull request merged**
