### PR TITLE
Fix pointer example

### PR DESCRIPTION
**Pull request by cheneym2**
Make the example shown for pointers something that would compile. Don't redefine pNext and do define MyType.

### CODE REVIEW

**Review by jkwak-work — APPROVED** [review]
Looks good for now.

**Comment by jkwak-work** [comment]
@cheneym2 , have you actually tried the example?
I am getting an error when I tried it,
```
(0): internal error 99999: Validation of generated SPIR-V failed.
```
The code I am using is following
```
//TEST(compute, vulkan):SIMPLE(filecheck=SPV): -stage compute -entry computeMain -target spirv -emit-spirv-directly

//TEST_INPUT:set inputBuffer = ubuffer(data=[1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0], stride=4)
RWByteAddressBuffer inputBuffer;

//TEST_INPUT:ubuffer(data=[0], stride=4):out,name=outputBuffer
RWStructuredBuffer<float> outputBuffer;

struct MyType
{
    float a;
};

float test(MyType* pObj)
{
    MyType* pNext = pObj + 1;
    MyType* pNext2 = &pNext[1];
    return pNext.a + pNext->a + (*pNext2).a + pNext2[0].a;
}

[numthreads(1,1,1)]
void computeMain()
{
    MyType data[2];
    data[0] = inputBuffer.Load<MyType>(0);
    data[1] = inputBuffer.Load<MyType>(4);
    outputBuffer[0] = test(&data[0]);
}
```

**Comment by jkwak-work** [comment]
@csyonghe , is the example expected to work?
What is the current status of pointer support?

**Comment by csyonghe** [comment]
It is supposed to demonstrate all syntaxes we allow. The example doesn't do anything that makes sense but we should be able to compile it without crashing.

**Comment by jkwak-work** [comment]
If it is expected to work, I will file a bug because it isn't working currently.

**Pull request merged**
