### PR TITLE
Update Slang-RHI to get recent WGPU fixes

### PR DESCRIPTION
**Pull request by aleino-nv**

### CODE REVIEW

**Review by csyonghe — DISMISSED** [review]

**Comment by csyonghe** [comment]
It feels like the new slang-rhi brought in some incompatible dxc compiler.

**Comment by aleino-nv** [comment]
> It feels like the new slang-rhi brought in some incompatible dxc compiler.

I'll check if `801865f` is the culprit.

    $ git log --oneline  ebc2b53ee9a06b73e26fa7ca6d2ee30fcf53b6d7..main
    edb9b72 (HEAD, origin/main, origin/HEAD, main) Add missing WGPU device tick after async map (#89)
    262d7a8 Add missing call to add descriptor ranges as constant buffer (#88)
    ad87777 fix string::format
    6386188 move acceleration structure utils (#86)
    801865f fetch dxc & agility sdk (#85)
    b322abb enable ci for aarch64 (#84)

**Comment by skallweitNV** [comment]
I'm adding a change that allows to disable fetching dxc and Agility SDK -> https://github.com/shader-slang/slang-rhi/pull/90

When that is merged, you can just set the following before `add_subdirectory(slang-rhi)`:

```cmake
set(SLANG_RHI_FETCH_DXC OFF)
set(SLANG_RHI_FETCH_AGILITY_SDK OFF)
```

**Comment by skallweitNV** [comment]
That said, we should probably check why the latest dxc version fails to compile those shaders ...

**Comment by aleino-nv** [comment]
> That said, we should probably check why the latest dxc version fails to compile those shaders ...

I filed https://github.com/shader-slang/slang/issues/5474 for this

**Comment by aleino-nv** [comment]
> I'm adding a change that allows to disable fetching dxc and Agility SDK -> [shader-slang/slang-rhi#90](https://github.com/shader-slang/slang-rhi/pull/90)
> 
> When that is merged, you can just set the following before `add_subdirectory(slang-rhi)`:
> 
> ```cmake
> set(SLANG_RHI_FETCH_DXC OFF)
> set(SLANG_RHI_FETCH_AGILITY_SDK OFF)
> ```

Yep, tests are passing when doing this and still pointing to RHI main ToT. 
Please have a look and approve if the CMake changes look fine.

**Review by expipiplus1 — APPROVED** [review]

**Pull request merged**
