### PR TITLE
Update spirv-tools version

### PR DESCRIPTION
**Pull request by cheneym2**

### CODE REVIEW

**Comment by jkwak-work** [comment]
I think you need to include external/spirv-tools-generated in this PR, isn't it?

**Comment by cheneym2** [comment]
> I think you need to include external/spirv-tools-generated in this PR, isn't it?

Maybe, I'm curious if the PR passes without that, but in any case, I will check to see what differences exist in the generated files.

**Review by jkwak-work — APPROVED** [review]
Looks good to me.

**Comment by jkwak-work** [comment]
> I was hasty and added the generated files to the PR before finding out if the checks would have passed. Anyways, PR is updated.

I was curious about it too.
But to share my experience, I was getting a compile error when I didn't update the generated files. That's when I learned that external/spirv-tools-generated existed.
So you may get lucky without updating it for this time, but I am pretty sure it is not a proper way to upgrade the spirv-header.

**Comment by csyonghe** [comment]
Yeah, I do think updating the generated files is needed.

**Review by csyonghe — APPROVED** [review]

**Pull request merged**
