### PR TITLE
Finish up implementation of render-test

### PR DESCRIPTION
**Pull request by csyonghe**
1. Pull texture data generation logic to shader-input-layout.cpp to share it across dx and gl renderers.
2. Implement the new Renderer interface in render-gl
3. Add new COMPARE_RENDER_COMPUTE test function, which runs pixel shader and compare UAV output results instead of framebuffer results.
4. Add a new COMPARE_RENDER_COMPUTE test case, testing sampling from all types of textures.

The opengl implementation cannot really work before we have a story for how slang deals with separated texture/sampler objects for glsl. This is a necessary feature to generate usable glsl shaders for OpenGL applications. My personal preference on this is to prioritize supporting separated texture/sampler objects for OpenGL over adding combined texture/samplers.

### CODE REVIEW

**Comment by csyonghe** [comment]
I have not tested the gl renderer yet. Tests that uses textures may not work since slang may not be generating the correct bindings. I will test it on some simple buffer read-write cases.

**Comment by tfoleyNV** [comment]
I would expect the GL bindings to be wrong (or at least not what you'd expect) since all of the logic in Slang's `type-layout.cpp` is specific to D3D12 and Vulkan right now. We'd have to add a separate mode for GL-compatible binding layout computation if we want to make it be what you'd expect.

Still, the Vulkan bindings should be usable, insofar as they just treat all types (uniform buffers, textures, etc.) as occupying a single binding space (so there will just be a lot of unused bindings when using GL).

I guess the bigger issue is combined texture/sampler support...

**Comment by csyonghe** [comment]
I think the bigger issue is to generate sampler object bindings for opengl. You need to analyze what texture objects are used with a sampler object, and report the sampler binding to be all the texture binding slots that is it used with.

**Comment by tfoleyNV** [comment]
Well, that's you jumping ahead to wanting to support OpenGL with separate textures/samplers, when I'm just talking about the combined case. :)

You should probably file an issue for that feature, since you really want it but it isn't a priority for Slang's current users.

**Pull request merged**
