### PR TITLE
Force Inline all stdlib functions

### PR DESCRIPTION
**Pull request by sriramm-nv**
Fixes #4003

### CODE REVIEW

**Comment by csyonghe** [comment]
I don't think we need to ForceInline all stdlib functions, only need to do so for the functions that can take resource parameters.

**Comment by jkwak-work** [comment]
The description says it fixes 4003 but 4003 is not an issue but PR.
I cannot find any information of what this change is trying to achieve.

**Comment by csyonghe** [comment]
The original intend here is that if the user has:
`resourceArray[NonUniformResourceIndex(index)].someMethodOnTheResource();`
Then `someMethodOnTheResource` must be [ForceInline]d for the non uniform resource pass to work for the spirv backend. If we see any resource memeber methods that are not forceinlined, we should make them so.

We should not be changing every stdlib function.

**Comment by csyonghe** [comment]
I am going to close this PR now, because I think there is a result of me not clearly communicating what is required.

**Pull request closed without merging**
