### PR TITLE
Replace stdlib on Slang API with CoreModule

### PR DESCRIPTION
**Pull request by jkwak-work**
This is a breaking change in a way that the Slang API function names are changed. All of them are commented as "experimental" and we wouldn't provide a back-ward compatibility for them.

Following functions are renamed:
 - compileStdLib() -> compileCoreModule()
 - loadStdLib() -> loadCoreModule()
 - saveStdLib() -> saveCoreModule()
 - slang_createGlobalSessionWithoutStdLib() -> slang_createGlobalSessionWithoutCoreModule()
 - slang_getEmbeddedStdLib() -> slang_getEmbeddedCoreModule()
 - hasDeferredStdLib() -> hasDeferredCoreModule()

Following command-line arguments are renamed:
 - "-load-stdlib" -> "-load-core-module"
 - "-save-stdlib" -> "-save-core-module"
 - "-save-stdlib-bin-source" -> "-save-core-module-bin-source"
 - "-compile-stdlib" -> "-compile-core-module"

### CODE REVIEW

**Comment by csyonghe** [comment]
-load-stdlib should be `-load-core-module`.

All current mention of stdlib in the compiler codebase should be changed to `core-module`. There should be no mention of standard modules in any of our source code files because everything we have is jsut the core module.

**Comment by jkwak-work** [comment]
> -load-stdlib should be `-load-core-module`.
> 
> All current mention of stdlib in the compiler codebase should be changed to `core-module`. There should be no mention of standard modules in any of our source code files because everything we have is jsut the core module.

I will change as suggested.

**Review by csyonghe — APPROVED** [review]

**Comment by csyonghe** [comment]
Also need to update docs/build_reference.ps1.

**Comment by jkwak-work** [comment]
This PR is for https://github.com/shader-slang/slang/issues/5335 but it doesn't close.
This PR is limited to "breaking changes".
I still need to work more on the issue.

**Pull request merged**
