### PR TITLE
Fix Lexer to recognize swizzling on an integer scalar value

### LINKED ISSUE #4413: Support HLSL swizzle operations
This feature request is for on-ramping. HLSL has a swizzle syntax that allow constants, temporaries, and, variables to swizzle to match the type of the expression. The swizzled expression can only use components up to their highest dimension.

This swizzling is commonly used. It would be helpful to have these operations supported for on-ramping.

**Shader: non-exhaustive list of swizzled expressions:**
```
RWTexture1D<uint4>   MyRWTexture;
RWTexture1D<float4>  MyRWTextureF;
void main() {
    MyRWTexture[0] = 0.xxxx;
    MyRWTexture[1] = uint2(0, 1).xyxy;
    MyRWTexture[2] = uint3(0, 1, 2).xxyz;
    MyRWTexture[3] = uint4(0, 1, 2, 3).wxyz;

    MyRWTextureF[0] = 0.12f.xxxx;
    MyRWTextureF[1] = float2(0, 1).xyxy;
    MyRWTextureF[2] = float3(0, 1, 2).xxyz;
    MyRWTextureF[3] = float4(0, 1, 2, 3).wxyz;

    MyRWTextureF[0] = 0.25.xxxx;

    float  s1;
    float2 s2;
    float3 s3;
    float4 s4;
    MyRWTextureF[0] = s1.xxxx + 0.xxxx;
    MyRWTextureF[1] = s2.xyxy + float2(0, 1).xyxy;
    MyRWTextureF[2] = s3.xxyz + float3(0, 1, 2).zyxy;
    MyRWTextureF[3] = s4.wxyz + float4(0, 1, 2, 4).zyxw;
}
```

### PR DESCRIPTION
**Pull request by jkwak-work**
Close #4413

### CODE REVIEW

**Review by ArielG-NV — DISMISSED** [review]
Code looks good to me.

Note:
I tested some prefixed/suffixed integer literals (`0x123.xxxx`, `0x123U.xxxx`, etc.), these work. I don't know if these should be in the tests.

**Comment by jkwak-work** [comment]
I am waiting for @csyonghe for a review.
I am not sure if we want to have a look ahead function for peeking two or more characters ahead at the lexer level.

**Review by csyonghe — APPROVED** [review]
Looks good. Does 1..xxx work?

It is a little unfortunate that we are duplicating the number parsing logic in two places, but it's fine for now.

**Comment by jkwak-work** [comment]
> Looks good. Does 1..xxx work?

Yes 1..xxx works as a floating type literal, which is expected.
I updated the test to include this form.

**Pull request merged**
