### PR TITLE
Add GL_EXT_ray_tracing_position_fetch capability

### PR DESCRIPTION
**Pull request by ArielG-NV**
This adds a previously separated capability `GL_EXT_ray_tracing_position_fetch_ray_tracing`/`GL_EXT_ray_tracing_position_fetch_ray_query` into 1 capability `GL_EXT_ray_tracing_position_fetch`

### CODE REVIEW

**Comment by ArielG-NV** [comment]
> Don't we also check in the generated files?

I don't quite understand the question.

**Comment by kaizhangNV** [comment]
I mean the generated source files: source/slang/slang-lookup-capability-defs.{cpp|h}.
Wondering that if we don't need to check in those files.

**Review by kaizhangNV — APPROVED** [review]
LGTM

**Comment by ArielG-NV** [comment]
> I mean the generated source files: source/slang/slang-lookup-capability-defs.{cpp|h}.

We do not check-in auto-generated files ([I don't see them inside the current source-tree](https://github.com/shader-slang/slang/tree/master/source/slang))

**Review by jkwak-work — APPROVED** [review]
Looks good to me.

**Pull request merged**
