### PR TITLE
Adjust how `slang` and `slangc` uses a `profile` to manage the stage of an entry-point

### LINKED ISSUE #4656: Unexpected crash when compiling using Slang API
I was using the API calls below before to compile shaders at runtime without a problem. Sorry, I don't remember which commit exactly. However, when I tried to windows release asset from slang-2024.1.30, I got a crash. I checked out the latest source from the repo to make sure it wasn't an issue with the release asset. 

When compiling the **psmain** from the shader below, I'm getting a crash in this stack:
```
>	slang.dll!std::optional<Slang::CapabilityAtomSet>::has_value() Line 391	C++
 	slang.dll!Slang::CapabilitySet::AtomSets::Iterator::operator bool() Line 211	C++
 	slang.dll!Slang::validateEntryPoint(Slang::EntryPoint * entryPoint, Slang::DiagnosticSink * sink) Line 533	C++
 	slang.dll!Slang::Module::_discoverEntryPoints(Slang::DiagnosticSink * sink, const Slang::List<Slang::RefPtr<Slang::TargetRequest>,Slang::StandardAllocator> & targets) Line 2586	C++
 	slang.dll!Slang::FrontEndCompileRequest::checkEntryPoints() Line 953	C++
 	slang.dll!Slang::FrontEndCompileRequest::checkAllTranslationUnits() Line 2824	C++
 	slang.dll!Slang::Linkage::loadParsedModule(Slang::RefPtr<Slang::FrontEndCompileRequest> compileRequest, Slang::RefPtr<Slang::TranslationUnitRequest> translationUnit, Slang::Name * name, const Slang::PathInfo & pathInfo) Line 3382	C++
 	slang.dll!Slang::Linkage::loadModule(Slang::Name * name, const Slang::PathInfo & filePathInfo, ISlangBlob * sourceBlob, const Slang::SourceLoc & srcLoc, Slang::DiagnosticSink * sink, const Slang::Dictionary<Slang::Name *,Slang::Module *,Slang::Hash<Slang::Name *>,std::equal_to<Slang::Name *>> * additionalLoadedModules, Slang::ModuleBlobType blobType) Line 3601	C++
 	slang.dll!Slang::Linkage::loadModuleFromBlob(const char * moduleName, const char * path, ISlangBlob * source, Slang::ModuleBlobType blobType, ISlangBlob * * outDiagnostics) Line 1221	C++
 	slang.dll!Slang::Linkage::loadModuleFromSource(const char * moduleName, const char * path, ISlangBlob * source, ISlangBlob * * outDiagnostics) Line 1247	C++
 	slang.dll!Slang::Linkage::loadModuleFromSourceString(const char * moduleName, const char * path, const char * source, ISlangBlob * * outDiagnostics) Line 1256	C++
 	101_color_cube_vulkan_slang.exe!CompileSlangSimple(const std::string & shaderSource, const std::string & entryPoint, const std::string & profile, std::vector<unsigned int,std::allocator<unsigned int>> * pSPIRV, std::string * pErrorMsg) Line 3334	C++
 	101_color_cube_vulkan_slang.exe!main(int argc, char * * argv) Line 153	C++
```

Can I get a sanity check to see if I'm missing something? I checked using `slangc` and the shader compiles with the **psmain** entry point without an issue.

**Shader**
```
struct CameraProperties {
    float4x4 MVP;
};

[[vk::push_constant]]
ConstantBuffer<CameraProperties> Cam;

struct VSOutput {
    float4 PositionCS : SV_POSITION;
    float3 Color      : COLOR;
};

[shader("vertex")]
VSOutput vsmain(float3 PositionOS : POSITION, float3 Color : COLOR0)
{
    VSOutput output = (VSOutput)0;
    output.PositionCS = mul(Cam.MVP, float4(PositionOS, 1));
    output.Color = Color;
    return output;
}

[shader("pixel")]
float4 psmain(VSOutput input) : SV_TARGET
{
    return float4(input.Color, 1);   
}
```

**API Function**
```
bool res = CompileSlangSimple(gShaders, "psmain", "ps_6_0", &spirvFS, &errorMsg);


bool CompileSlangSimple(
    const std::string&     shaderSource,
    const std::string&     entryPoint,
    const std::string&     profile,
    std::vector<uint32_t>* pSPIRV,
    std::string*           pErrorMsg)
{
    Slang::ComPtr<slang::IGlobalSession> globalSession;
    if (SLANG_FAILED(slang::createGlobalSession(globalSession.writeRef())))
    {
        return false;
    }

    slang::TargetDesc targetDesc = {};
    targetDesc.format            = SLANG_SPIRV;
    targetDesc.profile           = globalSession->findProfile(profile.c_str());
    targetDesc.flags             = SLANG_TARGET_FLAG_GENERATE_SPIRV_DIRECTLY;

    targetDesc.flags |= SLANG_TARGET_FLAG_GENERATE_WHOLE_PROGRAM;

    // Must be set in target desc for now
    targetDesc.forceGLSLScalarBufferLayout = true;

    // Compiler options for Slang
    std::vector<slang::CompilerOptionEntry> compilerOptions;
    {    
        // Force Slang language to prevent any accidental interpretations as GLSL or HLSL
        {
            slang::CompilerOptionEntry entry = {slang::CompilerOptionName::Language};
            entry.value.stringValue0         = "slang";

            compilerOptions.push_back(entry);
        }

        // Use specified entry point instead of main
        {
            compilerOptions.push_back(
                slang::CompilerOptionEntry{
                    slang::CompilerOptionName::VulkanUseEntryPointName,
                    slang::CompilerOptionValue{slang::CompilerOptionValueKind::Int, 1}
            });
        }
    }

    slang::SessionDesc sessionDesc       = {};
    sessionDesc.targets                  = &targetDesc;
    sessionDesc.targetCount              = 1;
    sessionDesc.defaultMatrixLayoutMode  = SLANG_MATRIX_LAYOUT_COLUMN_MAJOR;
    sessionDesc.compilerOptionEntries    = compilerOptions.data();
    sessionDesc.compilerOptionEntryCount = static_cast<uint32_t>(compilerOptions.size());

    Slang::ComPtr<slang::ISession> compileSession;
    if (SLANG_FAILED(globalSession->createSession(sessionDesc, compileSession.writeRef())))
    {
        return false;
    }

    // Load source
    slang::IModule* pSlangModule = nullptr;
    {
        Slang::ComPtr<slang::IBlob> diagBlob;
    
        pSlangModule = compileSession->loadModuleFromSourceString("grex-module", nullptr, shaderSource.c_str(), diagBlob.writeRef());
        if (pSlangModule == nullptr)
        {
            if (pErrorMsg != nullptr)
            {
                *pErrorMsg = std::string(static_cast<const char*>(diagBlob->getBufferPointer()), diagBlob->getBufferSize());
            }
    
            return false;
        }
    }

    return true;
}  
```

### PR DESCRIPTION
**Pull request by ArielG-NV**
Fixes #4656

Changes:
1. If the stage specified by a profile for a target is not equal to the stage specified by a entry-point, we throw a capability error.
2. Resolving the stage of an entry point was changed to function (mostly) equally for when 0 entry-points are specified versus to when there are 1 or more. This makes erroring locations consistent across the 2 methods to find entry-points.
3. Changed CapabilitySet Iterator so it is invalid if backing data is nullptr to avoid a potential crash. This should never happen unless validation fails, `[[unlikely]]` would be a nice-to-have for this change.

### CODE REVIEW

**Comment by jkwak-work** [comment]
It could be better if you were able to split your changes into smaller PRs.

**Comment by ArielG-NV** [comment]
> It could be better if you were able to split your changes into smaller PRs.

This PR solves the core problem of https://github.com/shader-slang/slang/issues/4656.
I believe I could have have 2 PRs, but then PR 1 would depend on PR 2. 

PR1 would have been the changes to `source/slang/slang-capability.h` (1 line of code)
* Errors would have been wrong, #4656 would still not be solved, but we would no longer crash.

PR2 would add diagnostics and fix how profiles are assigned to entry-points (all are required together, else the diagnostics added would have still been wrong)

**Comment by ArielG-NV** [comment]
I can still break the code into the 2 PRs if preferred for some reason in particular.

**Review by csyonghe — APPROVED** [review]

**Comment by jkwak-work** [comment]
I am not suggesting to break down the current PR because it will be a non trivial extra work. But please try to make your changes smaller next time which I have been telling multiple times already.

Incomplete implementation is not a big problem as long as it does cause a regression. The project is always incomplete anyway; from a bigger picture. The concept of complete and incomplete is how you define the problem domain.

Although my suggestion to make the PR smaller comes from the inconvenience for me as a reviewer, it has other benefits as well when the PR is limited to smaller size.

From a long term maintenance cost perspective, the readability is very important and when a commit is big, the readability goes down. Consider also that writing a code happens only once and reading and maintaining the code happens by the number of people who read the change throughout multiple years. Spending some time rewriting the code for better readability and maintainability in longer term will pay off eventually.

**Pull request merged**
