### PR TITLE
Allow implicit vector truncation (with a warning)

### LINKED ISSUE #502: Allow implicit vector truncation (with a warning)
There is enough code at there that expects `float4` to implicitly convert to `float3` that we need to either support it, or include a very detailed diagnostic that says something like "implicit vector truncation is not supported" (which would involve doing 99% of the work required in supporting the feature).

### PR DESCRIPTION
**Pull request by tfoleyNV**
Fixes #502

The main change here is to add initializers ("constructors") to `vector<T,N>` types that take a `vector<T,M>` where `M > N`, and mark those as valid implicit conversions.

I also added logic to the semantic checker to emit a warning whenever code performs implicit conversion using an initializer that has a cost over a certain level. This ensures that the user will get warned if they do an unsafe implicit conversion.

As one more fix, I noticed that `uint` to `int` conversion was generating the warning, because we were treating it as a "general" conversion, but there are a lot of places that rely on that conversion so warning would create problems. I changed the cost of same-size signed-to-unsigned conversations to be lower, and actually lower than integer-to-float conversions.

When testing, I cound that one of our existing test cases was relying on implicit `float`-to-`int` conversion and now generates a warning. That seems reasonable, and I fixed the test case to do an explicit conversion instead.

### CODE REVIEW

**Comment by tfoleyNV** [comment]
@csyonghe We need to decide whether to merge this change or not. Allowing “bad” implicit conversions by default may be a door we don’t want to open.

**Comment by csyonghe** [comment]
I guess this is for HLSL compatibility? For things like this we might be able to support via a separate "compatibility" compiler mode and don't enable it by default.

**Comment by tfoleyNV** [comment]
Yes. @jsmall-nvidia and I talked about this a bit, and agreed that maybe we won't merge this PR just yet, *unless* the current users start complaining about it.

A better version of this PR would include the kind of "compatibility flag" you are talking about, but adding that would be work that I might prefer to avoid compared to just making the default mode as good as possible.

One detail from this PR that might be worth keeping, though, is the warning it adds for implicit `float`->`int` conversions, which were otherwise being allowed silently. So maybe I should pick up this PR and modify it so that it just does the warning behavior without also adding the new implicit conversions for vectors.

**Comment by tfoleyNV** [comment]
Closing for now since users haven’t been demanding this feature and the Slang development team isn’t excited about opening the door to doing “bad” conversions implicitly.

We can resurrect certain bits later if we decide it is worth it.

**Pull request closed without merging**
