### PR TITLE
Enable full test on macos.

### LINKED ISSUE #4328: Disable all failing metal tests and enable full testing on CI.

### PR DESCRIPTION
**Pull request by csyonghe**
Closes #4328.

### CODE REVIEW

**Comment by skallweitNV** [comment]
That won't work yet. I only disabled crashing tests, not ones that generate incorrect results.

**Comment by csyonghe** [comment]
I see. We need to disable them as well so we can enable this. I am also not sure whether those gfx unit tests will work.

**Comment by skallweitNV** [comment]
Ok, lets first merge #4326 and then disable the list at the bottom of #4291

**Comment by skallweitNV** [comment]
Actually you should probably just disable those tests as part of this PR

**Comment by csyonghe** [comment]
Yeah, will do that.

**Pull request merged**
