### PR TITLE
Feature/slang command line tests

### PR DESCRIPTION
**Pull request by jsmall-nvidia**
* Added COMMAND_LINE_SIMPLE test type
* Made how spawning works controllable by parameter/type SpawnType
* Made break-outside-loop and global-uniform run command line slangc

### CODE REVIEW

**Comment by tfoleyNV** [comment]
@jsmall-nvidia When I try to review this PR I don't see any diffs. Even now looking at the quick summary information I see 3 commits and 0 files changed.

**Comment by jsmall-nvidia** [comment]
Oh that maybe because the hash branch, was a branch from this. So I guess it's my mistake - that if I'm going to do that I have to merge in the order of the branching.

**Comment by tfoleyNV** [comment]
I see. So we can close this PR because the changes were already reviewed and merged as part of the other one?

**Comment by tfoleyNV** [comment]
Closing since there is nothing to be merged at this point.

**Pull request closed without merging**
