### PR TITLE
Document the interfaces in the core module

### PR DESCRIPTION
**Pull request by jkwak-work**
Closes https://github.com/shader-slang/slang/issues/5304

### CODE REVIEW

**Comment by jkwak-work** [comment]
I tried to locally preview the result but I couldn't figure how to generate Gemfile.

I was able to install jekyll with a few tries and errors on WSL.
```
sudo apt update
sudo apt-get install ruby-full
sudo gem update
sudo gem install jekyll bundler
jekyll -v
```
But I couldn't figure how to generate Gemfile.

I guess I failed to understand what "Create a Jekyll site." means in the [instruction page](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll).

**Comment by jkwak-work** [comment]
I am not sure if this is a proper way to generate Gemfile but I tried a following, and it gave me an error.
```
$ jekyll new --skip-bundle .
 Conflict: /mnt/d/sbf/git/slang/stdlib-reference exists and is not empty.
                    Ensure /mnt/d/sbf/git/slang/stdlib-reference is empty or else try again with `--force` to proceed and overwrite any files.
```
As suggested on the error message, I tried "--force" option, and it generated Gemfile.
```
$ jekyll new --skip-bundle . --force
New jekyll site installed in /mnt/d/sbf/git/slang/stdlib-reference.
Bundle install skipped.
$ sudo bundle install
$ bundle exec jekyll serve
Configuration file: /mnt/d/sbf/git/slang/stdlib-reference/_config.yml
            Source: /mnt/d/sbf/git/slang/stdlib-reference
       Destination: /mnt/d/sbf/git/slang/stdlib-reference/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /mnt/d/sbf/git/slang/stdlib-reference/_site/index.html
                     - index.markdown
                     - index.md

                    done in 64.016 seconds.
 Auto-regeneration: enabled for '/mnt/d/sbf/git/slang/stdlib-reference'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```
While the web service is running, I tried to access http://127.0.0.1:4000 but it gave me an error saying "This page is not working".

**Comment by jkwak-work** [comment]
chatGPT helped me to figure out what went wrong.
It had to do the fact that I was unning jekyll from WSL and the web browser was running on Windows native system.
The IP address didn't work correctly.
I did the following to resolve it.
```
# On WSL side
$ rm index.markdown
$ hostname -I
172.28.162.172
$ bundle exec jekyll serve --host 0.0.0.0
Configuration file: /mnt/d/sbf/git/slang/stdlib-reference/_config.yml
            Source: /mnt/d/sbf/git/slang/stdlib-reference
       Destination: /mnt/d/sbf/git/slang/stdlib-reference/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
                    done in 63.568 seconds.
 Auto-regeneration: enabled for '/mnt/d/sbf/git/slang/stdlib-reference'
    Server address: http://0.0.0.0:4000/
  Server running... press ctrl-c to stop.
```
Then I access the web page from `http://172.28.162.172:4000/`.
Some pages are showing up but some links are not working yet.
I am still trying to figure out why it doesn't fully work.

**Comment by jkwak-work** [comment]
I will add some examples and add more information about the immutability as Elli pointed out

**Review by csyonghe — APPROVED** [review]

**Pull request merged**
