### PR TITLE
format cmake files

### LINKED ISSUE #5388: Format all CMake files
- [x] Review the two popular cmake formatters, cmake-format and gersemi
- [ ] Document formatting procedure
- [ ] CI checks for CMake formatting

### PR DESCRIPTION
**Pull request by expipiplus1**
closes #5388

### CODE REVIEW

**Review by csyonghe — APPROVED** [review]

**Comment by expipiplus1** [comment]
/format

let's give this a try...

**Comment by expipiplus1** [comment]
https://github.com/peter-evans/slash-command-dispatch/issues/267 ran into this, will regenerate the token

**Comment by expipiplus1** [comment]
(This is now back at the state it was when @csyonghe reviewed it, so i'll merge when the CI passes)

**Pull request merged**
