### PR TITLE
Fill out support for calls to non-decl values

### PR DESCRIPTION
**Pull request by tangent-vector**
The existing compiler logic has a few places (semantic checking plus AST-to-IR lowering) where it assumes that function calls (`InvokeExpr`) are only ever made to expressions that resolve to a specific `Decl` (`DeclRefExpr`). This assumption allows semantic checking and lowering code to inspect things like the parameter list of an actual declaration, rather than just the type signature of the callee, and that infrastructure is used to support various features (e.g., default argument values on parameters).

The AST and IR representations themselves have no matching requirement, and the places where the more general case of call expressions would need to be supported were relatively clear in the code. This change attempts to add suitable logic into each of those places.

Note that this change does *not* surface any valid way to form input code that would cause these new code paths to be executed, so it is entirely possible that there are bugs in the logic as written here. The primary goal of this change is simply to get a sketch of the correct code checked in so that we have something to build on once we have language features that will require this support.

### CODE REVIEW

**Review by csyonghe — APPROVED** [review]
Looks good. Thanks for implementing this so quickly!

**Review by saipraveenb25 — DISMISSED** [review]
Looks good to me! 
(Although some windows tests aren't passing because of unreferenced variable?)

**Review by saipraveenb25 — APPROVED** [review]
I think it's fixed now

**Comment by csyonghe** [comment]
Closing as this is subsumed by #2292

**Pull request closed without merging**
