### PR TITLE
Support 64bit HLSL atomic functions

### LINKED ISSUE #3951: Support 64bit integer type for HLSL InterlockedXXX function set
We don't have 64bit integer type support for InterlockedXXX function set.
The existing ones are for 32bit integer types.
This causes compile errors on UE 5.3.2 TSR shaders.

Although UE only uses one of the functions, "InterlockedAdd()", it will be a good idea to implement all related function set described in the following URL.
https://microsoft.github.io/DirectX-Specs/d3d/HLSL_SM_6_6_Int64_and_Float_Atomics.html

```
void InterlockedAdd(inout XXX dest, in int64_t value, out int64_t original_value);
void InterlockedAdd(inout XXX dest, in uint64_t value, out uint64_t original_value);
void InterlockedAnd(inout XXX dest, in uint64_t value, out uint64_t original_value);
void InterlockedOr(inout XXX dest, in uint64_t value, out uint64_t original_value);
void InterlockedXor(inout XXX dest, in uint64_t value, out uint64_t original_value);
void InterlockedMin(inout XXX dest, in int64_t value, out int64_t original_value);
void InterlockedMin(inout XXX dest, in uint64_t value, out uint64_t original_value);
void InterlockedMax(inout XXX dest, in int64_t value, out int64_t original_value);
void InterlockedMax(inout XXX dest, in uint64_t value, out uint64_t original_value);
void InterlockedExchange(inout XXX dest, in float value, out float original_value);
void InterlockedExchange(inout XXX dest, in int64_t value, out int64_t original_value);
void InterlockedExchange(inout XXX dest, in uint64_t value, out uint64_t original_value);
void InterlockedCompareStore(inout XXX dest, in int64_t compare_value, in int64_t value);
void InterlockedCompareStore(inout XXX dest, in uint64_t compare_value, in uint64_t value);
void InterlockedCompareStoreFloatBitwise(inout XXX dest, in float compare_value, in float value);
void InterlockedCompareExchange(inout XXX dest, in int64_t compare_value, in int64_t value, out int64_t original_value);
void InterlockedCompareExchange(inout XXX dest, in uint64_t compare_value, in uint64_t value, out uint64_t original_value);
void InterlockedCompareExchangeFloatBitwise(inout XXX dest, in float compare_value, in float value, out float original_value);
```
Note that "original_value" is an optional argument that can be omitted.
And the following member functions need to be added too.
```
void RWByteAddressBuffer::InterlockedAnd64(in uint dest_offset, in uint64_t value, out uint64_t original_value);
void RWByteAddressBuffer::InterlockedOr64(in uint dest_offset, in uint64_t value, out uint64_t original_value);
void RWByteAddressBuffer::InterlockedXor64(in uint dest_offset, in uint64_t value, out uint64_t original_value);
void RWByteAddressBuffer::InterlockedMin64(in uint dest_offset, in int64_t value, out int64_t original_value);
void RWByteAddressBuffer::InterlockedMin64(in uint dest_offset, in uint64_t value, out uint64_t original_value);
void RWByteAddressBuffer::InterlockedMax64(in uint dest_offset, in int64_t value, out int64_t original_value);
void RWByteAddressBuffer::InterlockedMax64(in uint dest_offset, in uint64_t value, out uint64_t original_value);
void RWByteAddressBuffer::InterlockedExchangeFloat(in uint dest_offset, in float value, out float original_value);
void RWByteAddressBuffer::InterlockedExchange64(in uint dest_offset, in int64_t value, out int64_t original_value);
void RWByteAddressBuffer::InterlockedExchange64(in uint dest_offset, in uint64_t value, out uint64_t original_value);
void RWByteAddressBuffer::InterlockedCompareStore64(in uint dest_offset, in int64_t compare_value, in int64_t value);
void RWByteAddressBuffer::InterlockedCompareStore64(in uint dest_offset, in uint64_t compare_value, in uint64_t value);
void RWByteAddressBuffer::InterlockedCompareStoreFloatBitwise(in uint dest_offset, in float compare_value, in float value);
void RWByteAddressBuffer::InterlockedCompareExchangeFloatBitwise(in uint dest_offset, in float compare_value, in float value, out float original_value);
```

### PR DESCRIPTION
**Pull request by jkwak-work**
Resolves #3951

This adds a few atomic functions for SM6.6.
The spec can be found from here:
https://microsoft.github.io/DirectX-Specs/d3d/HLSL_SM_6_6_Int64_and_Float_Atomics.html

### CODE REVIEW

**Review by csyonghe — APPROVED** [review]
We need to fill in the impl for vulkan and cuda as well.

**Comment by ArielG-NV** [comment]
seeing the PR was merged:

Shader capabilities will need to be filled, WIP PR `https://github.com/shader-slang/slang/pull/3907` will handle this.

to add GLSL/SPIR-V/CUDA we will likely restructure the code to allow reuse with glsl.meta atomic code (supports int64).

**Comment by csyonghe** [comment]
@ArielG-NV Yeah we need to change glsl.meta.slang to call into the HLSL functions instead.

**Comment by Ipotrick** [comment]
I just saw this issue. Did i read correctly that this does not implement 64 bit atomics for spirv out? I need 64 bit atomics for spirv out.

**Comment by ArielG-NV** [comment]
This implements for hlsl 64 bit atomics.

**Comment by ArielG-NV** [comment]
for example: `void InterlockedAdd64(uint byteAddress, int64_t valueToAdd)` supports glsl/spirv

**Comment by ArielG-NV** [comment]
glsl syntax (`allow-glsl` flag) supports glsl/spirv atomics fully for whatever glsl implemented.

**Pull request merged**
