### PR TITLE
Correctly identify the number of operands to image sampling operands in SPIR-V

### PR DESCRIPTION
**Pull request by expipiplus1**

### CODE REVIEW

**Review by csyonghe — APPROVED** [review]

**Comment by expipiplus1** [comment]
👀 One of these failing in only one config on CI days...

**Comment by csyonghe** [comment]
I think it is probably just swift-shader doesn't support mesh shaders. You need to add a -render-feature flag in the test to disable it when mesh shader isn't reported as supported.

**Comment by csyonghe** [comment]
> I think it is probably just swift-shader doesn't support mesh shaders. You need to add a -render-feature flag in the test to disable it when mesh shader isn't reported as supported.

Oh wait, this isn't even the mesh shader PR...

**Comment by csyonghe** [comment]
Due to recent github image and tool chain updates, I can no longer build a working swift shader binary on linux. It would be good to figure out how to re-enable it on linux.

**Comment by expipiplus1** [comment]
I can reproduce the failure on Linux with swiftshader 2020-11-06 and 2023-09-11.

texture-simpler does work, however and isn't doing anything meaningfully different.

**Pull request merged**
