### PR TITLE
Fix wgsl legalization around __ref parameter.

### LINKED ISSUE #5596: [WGSL] `__ref` does not work as expected
`__ref` parameters do not work correctly. Objects passed as reference to function should not be placed in a local variable.

The following test replicates this behavior

```csharp
// groupshared-ref-param.slang

//TEST:SIMPLE(filecheck=CHECK): -target wgsl -entry computeMain -stage compute


//TEST_INPUT:ubuffer(data=[0 0 0 0], stride=4):out,name=outputBuffer
RWStructuredBuffer<int> outputBuffer;

groupshared uint sharedVal;

[ForceInline]
uint workgroupUniformLoad(__ref uint val)
{
    __intrinsic_asm "workgroupUniformLoad(&($0))";
}

// Expect sharedVal to be passed by reference.
//
// CHECK: fn computeMain({{.*}}({{.*}})
// CHECK: {{.*}}workgroupUniformLoad(&((sharedVal_{{[a-zA-Z0-9_]*}}))){{.*}};
// CHECK: }


[numthreads(1, 1, 1)]
void computeMain(int3 dispatchThreadID: SV_DispatchThreadID)
{
    int idx = dispatchThreadID.x;

    sharedVal = 1;
    outputBuffer[0] = workgroupUniformLoad(sharedVal);
}
```

WGSL output: 
```csharp
@binding(0) @group(0) var<storage, read_write> outputBuffer_0 : array<i32>;

var<workgroup> sharedVal_0 : u32;

@compute
@workgroup_size(1, 1, 1)
fn computeMain(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>)
{
    sharedVal_0 = u32(1);
    var _S1 : u32 = u32(1);
    var _S2 : u32 = (workgroupUniformLoad(&((_S1))));
    sharedVal_0 = _S1;
    outputBuffer_0[i32(0)] = i32(_S2);
    return;
}
```

HLSL output (this works as expected):
```csharp
#pragma pack_matrix(column_major)
#ifdef SLANG_HLSL_ENABLE_NVAPI
#include "nvHLSLExtns.h"
#endif

#ifndef __DXC_VERSION_MAJOR
// warning X3557: loop doesn't seem to do anything, forcing loop to unroll
#pragma warning(disable : 3557)
#endif


#line 9 "tests/language-feature/pointer/groupshared-ref-param.slang"
RWStructuredBuffer<int > outputBuffer_0 : register(u0);

static groupshared uint sharedVal_0;


#line 34
[numthreads(1, 1, 1)]
void computeMain(int3 dispatchThreadID_0 : SV_DispatchThreadID)
{

    sharedVal_0 = 1U;
    uint _S1 = (workgroupUniformLoad(&((sharedVal_0))));

#line 39
    outputBuffer_0[int(0)] = int(_S1);
    return;
}
```

### PR DESCRIPTION
**Pull request by csyonghe**
Closes #5596.

### CODE REVIEW

**Comment by saipraveenb25** [comment]
Looks good to me!

Maybe add the test code in the issue as a test?

**Review by saipraveenb25 — APPROVED** [review]

**Review by jkwak-work — DISMISSED** [review]
Looks good to me.
It seems like the issue has a repo case.
Can we use it for testing, if we don't already have it yet?

**Comment by csyonghe** [comment]
@jkwak-work we are going to add more intrinsics using that rely on this fix, so it shall be covered when those intrinsics are added in a separate PR.

**Comment by jkwak-work** [comment]
> @jkwak-work we are going to add more intrinsics using that rely on this fix, so it shall be covered when those intrinsics are added in a separate PR.

I see.

**Comment by csyonghe** [comment]
@jkwak-work @saipraveenb25 I added the intrinsic and the test case.

**Review by jkwak-work — APPROVED** [review]
Looks good to me

**Pull request merged**
