### PR TITLE
Legalize the Entry-point for WGSL

### LINKED ISSUE #5486: [WGSL] Binding keywords are missing for a vertex shader entry-point
**Problem description**
When targeting WGSL, Slang generates an invalid return type for the vertex shader entry-point.
The binding keywords such as `@location` and `@builtin` are missing.

**Repo steps**
The following simple shader can reproduce the issue,
```
struct VertexOutput {
    float4 position : SV_Position;
    float4 color : TEXCOORD0;
};

VertexOutput vertexMain() {
    VertexOutput out;
    out.position = float4(1.0, 1.0, 1.0, 1.0);
    out.color = float4(0.0, 0.0, 0.0, 0.0);
    return out;
}
```
Slang currently generates the following WGSL with a command "slangc -target wgsl -entry vertexMain -stage vertex simple.slang",
```
struct VertexOutput_0
{
     position_0 : vec4<f32>,
     color_0 : vec4<f32>,
};

@vertex
fn vertexMain() -> VertexOutput_0
{
    var out_0 : VertexOutput_0;
    out_0.position_0 = vec4<f32>(1.0f, 1.0f, 1.0f, 1.0f);
    out_0.color_0 = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
    return out_0;
}
```
The correct output should have the binding keywords in the struct, `VertexOutput_0`, as following,
```
struct VertexOutput_0
{
     @builtin(position) position_0 : vec4<f32>,
     @location(0) color_0 : vec4<f32>,
};
```

### PR DESCRIPTION
**Pull request by jkwak-work**
Closes #5486

The return type of the entry-point needs to be legalized when targeting WGSL.
This commit flattens the nested-structs of the return type and the input parameters of the entry-point.

Most of code is copied from the legalization code for Metal. The following functions are exactly same to the implementation for Metal or almost same.
- flattenInputParameters() : 136 lines
- reportUnsupportedSystemAttribute() : 7 lines
- ensureResultStructHasUserSemantic() : 46 lines
- struct MapStructToFlatStruct : 176 lines
- flattenNestedStructs() : 95 lines
- maybeFlattenNestedStructs() : 42 lines
- _replaceAllReturnInst() : 19 lines
- _returnNonOverlappingAttributeIndex() : 16 lines
- _replaceAttributeOfLayout() : 23 lines
- tryConvertValue() : 41 lines
- legalizeSystemValueParameters() : 11 lines

They need to be refactored to reduce the duplication later.

### CODE REVIEW

**Comment by jkwak-work** [comment]
For the review, `source/slang/slang-ir-wgsl-legalize.cpp` is better to be compared to `source/slang/slang-ir-metal-legalize.cpp`.

**Review by csyonghe — DISMISSED** [review]
Looks good. We definitely need to refactor this to reuse as much code as possible between the  two backends.

**Comment by jkwak-work** [comment]
It seems like `tests/compute/assoctype-lookup.slang` is failing because of this change.
I am looking into it now.

**Comment by csyonghe** [comment]
Can we also turn on all the relevant tests we have for metal to also cover wgsl?

**Comment by jkwak-work** [comment]
> Can we also turn on all the relevant tests we have for metal to also cover wgsl?

I see. That's a good idea.
Let me do that.

**Pull request merged**
