### PR TITLE
Parameter layout and reflection for Metal bindings.

### LINKED ISSUE #4012: Properly handle parameter layout in the Metal backend.
We need to implement metal specific parameter layout / reflection and code emit logic to correctly decorate shader parameters with their binding indices in Metal.

We also need to figure out how argument buffer works in metal, and how to map ParameterBlock<T> or ConstantBuffer<T> to argument buffers.

### PR DESCRIPTION
**Pull request by csyonghe**
Closes #4012.

Metal has only three types of bindings: `buffer`, `texture` and `sampler`.
In addition, it has `argument buffer` which is itself a `buffer`, but any further resource members of the argument buffer does not occupy any explicit binding points, and instead set via an offset within the buffer referred to as `id` in the metal spec.

Slang's `ParameterBlock` maps to argument buffers naturally. We introduce a new ParameterCategory called `MetalArgumentBufferElement` to represent the `id` of a parameter block element.

With this change, given shader:
```
uniform RWStructuredBuffer<float> outputBuffer;

struct MyBlock
{
    StructuredBuffer<float> b1;
    StructuredBuffer<float> b2;
}
ParameterBlock<MyBlock> block;
ParameterBlock<MyBlock> block2;

void func(float v)
{
    outputBuffer[0] = v;
    outputBuffer[1] = outputBuffer.Load(0);
    outputBuffer[2] = block.b1[0] + block2.b2[0];
}

[numthreads(1,1,1)]
void main_kernel()
{
    func(3.0f);
}
```

We can get this reflection result:
```
    "parameters": [
        {
            "name": "outputBuffer",
            "binding": {"kind": "constantBuffer", "index": 0},
            "type": {
                "kind": "resource",
                "baseShape": "structuredBuffer",
                "access": "readWrite",
                "resultType": {
                    "kind": "scalar",
                    "scalarType": "float32"
                }
            }
        },
        {
            "name": "block",
            "binding": {"kind": "constantBuffer", "index": 1},
            "type": {
                "kind": "parameterBlock",
                "elementType": {
                    "kind": "struct",
                    "name": "MyBlock",
                    "fields": [
                        {
                            "name": "b1",
                            "type": {
                                "kind": "resource",
                                "baseShape": "structuredBuffer",
                                "resultType": {
                                    "kind": "scalar",
                                    "scalarType": "float32"
                                }
                            },
                            "binding": {"kind": "metalArgumentBufferElement", "index": 0}
                        },
                        {
                            "name": "b2",
                            "type": {
                                "kind": "resource",
                                "baseShape": "structuredBuffer",
                                "resultType": {
                                    "kind": "scalar",
                                    "scalarType": "float32"
                                }
                            },
                            "binding": {"kind": "metalArgumentBufferElement", "index": 1}
                        }
                    ]
                },
                "containerVarLayout": {
                    "binding": {"kind": "constantBuffer", "index": 0}
                },
                "elementVarLayout": {
                    "type": {
                        "kind": "struct",
                        "name": "MyBlock",
                        "fields": [
                            {
                                "name": "b1",
                                "type": {
                                    "kind": "resource",
                                    "baseShape": "structuredBuffer",
                                    "resultType": {
                                        "kind": "scalar",
                                        "scalarType": "float32"
                                    }
                                },
                                "binding": {"kind": "metalArgumentBufferElement", "index": 0}
                            },
                            {
                                "name": "b2",
                                "type": {
                                    "kind": "resource",
                                    "baseShape": "structuredBuffer",
                                    "resultType": {
                                        "kind": "scalar",
                                        "scalarType": "float32"
                                    }
                                },
                                "binding": {"kind": "metalArgumentBufferElement", "index": 1}
                            }
                        ]
                    },
                    "binding": {"kind": "metalArgumentBufferElement", "index": 0, "count": 2}
                }
            }
        },
        {
            "name": "block2",
            "binding": {"kind": "constantBuffer", "index": 2},
            "type": {
                "kind": "parameterBlock",
                "elementType": {
                    "kind": "struct",
                    "name": "MyBlock",
                    "fields": [
                        {
                            "name": "b1",
                            "type": {
                                "kind": "resource",
                                "baseShape": "structuredBuffer",
                                "resultType": {
                                    "kind": "scalar",
                                    "scalarType": "float32"
                                }
                            },
                            "binding": {"kind": "metalArgumentBufferElement", "index": 0}
                        },
                        {
                            "name": "b2",
                            "type": {
                                "kind": "resource",
                                "baseShape": "structuredBuffer",
                                "resultType": {
                                    "kind": "scalar",
                                    "scalarType": "float32"
                                }
                            },
                            "binding": {"kind": "metalArgumentBufferElement", "index": 1}
                        }
                    ]
                },
                "containerVarLayout": {
                    "binding": {"kind": "constantBuffer", "index": 0}
                },
                "elementVarLayout": {
                    "type": {
                        "kind": "struct",
                        "name": "MyBlock",
                        "fields": [
                            {
                                "name": "b1",
                                "type": {
                                    "kind": "resource",
                                    "baseShape": "structuredBuffer",
                                    "resultType": {
                                        "kind": "scalar",
                                        "scalarType": "float32"
                                    }
                                },
                                "binding": {"kind": "metalArgumentBufferElement", "index": 0}
                            },
                            {
                                "name": "b2",
                                "type": {
                                    "kind": "resource",
                                    "baseShape": "structuredBuffer",
                                    "resultType": {
                                        "kind": "scalar",
                                        "scalarType": "float32"
                                    }
                                },
                                "binding": {"kind": "metalArgumentBufferElement", "index": 1}
                            }
                        ]
                    },
                    "binding": {"kind": "metalArgumentBufferElement", "index": 0, "count": 2}
                }
            }
        }
    ],
    "entryPoints": [
        {
            "name": "main_kernel",
            "stage:": "compute",
            "threadGroupSize": [1, 1, 1],
            "bindings": [
                {
                    "name": "outputBuffer",
                    "binding": {"kind": "constantBuffer", "index": 0, "used": 0}
                },
                {
                    "name": "block",
                    "binding": {"kind": "constantBuffer", "index": 1, "used": 0}
                },
                {
                    "name": "block2",
                    "binding": {"kind": "constantBuffer", "index": 2, "used": 0}
                }
            ]
        }
    ]
```

### CODE REVIEW

**Comment by jkwak-work** [comment]
How did you print the data in Jason format?

**Comment by csyonghe** [comment]
@jkwak-work  This is the result from running the `REFLECTION` test, and implemented in the slang-reflection-test-main.cpp as part of the `slang-reflection-test-tool`.

**Comment by jkwak-work** [comment]
> @jkwak-work This is the result from running the `REFLECTION` test, and implemented in the slang-reflection-test-main.cpp as part of the `slang-reflection-test-tool`.

Yes, I realized it after reviewing the change to the bottom.
Thanks for the reply tho.

**Review by jkwak-work — APPROVED** [review]
Looks good to me.

**Pull request merged**
