### PR TITLE
Parameter blocks

### PR DESCRIPTION
**Pull request by tfoleyNV**
Creating a pull request to track progress on implementing `ParameterBlock<T>` (rather than trying to break it into a bunch of small PRs).

### CODE REVIEW

**Comment by tfoleyNV** [comment]
Thinking it through, it seems like the approach previous change takes for dealing with aggregate types that mix resource and non-resource fields is all wrong. Rather than replacing individual variables and then chasing down their uses, we should do something a bit more systematic and have a type "legalization" pass that proceeds through the entire IR module, top-down.

This needs to be done *after* specialization and de-virtualization is complete, so that we always know where the mixed-type aggregates are to be found. Such aggregates should get legalized into "tuple" types over their field types (similar to what is already done in `lower.cpp`).

The big question on that front is whether this should involve adding tuple types to the type system so that legalization produces them directly (after which other passes clean them up), or if we should use an out-of-band representation (similar again to `lower.cpp`).

Aside: Note that this kind of scalarization is distinct from the scalarization that gets applied to varying input/output for GLSL, because in that case the type is legal in general, but not legal for certain uses.

**Comment by csyonghe** [comment]
@tfoleyNV this fails to build.

**Comment by tfoleyNV** [comment]
@csyonghe Yep. This PR isn’t ready to merge yet, and I’m just creating it so that you and Kayvon can have visibility into the changes as I make them.

**Comment by tfoleyNV** [comment]
If the tests pass, I'd like to check in this work as a checkpoint. There's still some major things left to do, though:

- There's no work being done to handle uniform data inside of `T` for `ParameterBlock<T>`. My initial thinking is that the best way to handle that scenario is to actually lay out such a type as if it had been written `ParameteBlock<ConstantBuffer<T>>` and expose it that way through reflection, so that the application can respond appropriately.

- There's no testing here that nesting of parameter blocks works. E.g., what if you have `ParameterBlock<X>` where `X` contains a `ParameterBlock<Y>`? The expected layout is clear, but we need a test to make sure it actually work.

- We need a fallback plan here for D3D11 and GL, so that we can run code that uses parameter blocks on those APIs (since that is what our testing curently uses). My sense is that the Right Way to handle this is during the type-layout step; if we detect a GL target, or an HLSL target of SM5.0 or lower, then we should *not* handle parameter blocks specially, and instead should lay `ParameterBlock<T>` out *exactly* like we would `ConstantBuffer<T>` (*maybe* with some special casing for when `T` has no uniform data...). This means that nested resource declarations wouldn't get their own space/set.

- For Falcor's requirements, we need to support `ParameterBlock` as part of the type desugaring that is done in `lower.cpp` today. Ideally I'd like to find a way to merge that logic in with what `ir-lower-types.cpp` is already doing, to avoid duplication.

- One other Falcor-related point is that the type lowering for mixed uniform+resource types that was implement before tried to keep the output as clean as possible by not scalarizing uniform fields (keeping them in a `struct` type that has just been stripped of resource fields). It might be nice for the IR type lowering to do the same trick, so we get cleaner output that lines up with the current AST-to-AST transform.

- I haven't tested how any of this stuff works with arrays, but there are a lot of type layout and resource-binding questions around arrays that need to get nailed down in general. One important point here is that when generating code for HLSL SM5.1 and up, we should actually allocate an unbounded-size array its own `space`

- Eventually we need to support `ParameterBlock<T>` in the case where `T` is a generic type parameter of an entry-point, or when `T` is an interface type (if we allow the syntax sugar case for global-scope parameter block declarations).

**Comment by csyonghe** [comment]
Let's get it checked in.

**Pull request merged**
