### PR TITLE
Update SPIRV submodules

### PR DESCRIPTION
**Pull request by jkwak-work**
Closes https://github.com/shader-slang/slang/issues/5573

One of tests started failing with the latest SPIR-V submodules:
`tests/gpu-feature/texture/query/footprint/nv-shader-texture-footprint.slang`

`[ForceInline]` is added to GLSL texture functions in order to inline `%true` and `%false`.
Without it, the value was indirectly passed down via a function parameter, which broke the existing test.

Also the test is modified to use `-DAG`, because the order unpredictably changed for `Grad` variants due to additional `[ForceInline]` marks for Gradient functions.

### CODE REVIEW

**Comment by csyonghe** [comment]
The test still has validation error on linux and macos?

**Comment by jkwak-work** [comment]
I will work on the CI failures on Linux and MacOS

**Comment by jkwak-work** [comment]
It turned out that the Windows build is also not working properly.
The cause of the failure is that the test starts having a Vulkan Validation Error, which was introduced three month ago in SPIRV-Tools repo:
https://github.com/KhronosGroup/SPIRV-Tools/commit/7ba72f14f2f59a6f65465e5fb3e849dc81ae462d
The description of the commit is here,
```
spirv-val: Disallow stores according to VUID 06924 (https://github.com/KhronosGroup/SPIRV-Tools/pull/5368)
Ensure that the validator rejects stores to objects of types
`OpTypeImage`, `OpTypeSampler`, `OpTypeSampledImage`,
`OpTypeAccelerationStructureKHR`, and arrays of these types, according
to `VUID-StandaloneSpirv-OpTypeImage-06924`.

Guard the check behind the before_hlsl_legalization option, as
sometimes we may have temporaries or local variables that are expected
to get optimized away.
```

I will file an issue for this.

**Comment by jkwak-work** [comment]
I applied Ellie's fix and all CI tests are now passing.

**Review by csyonghe — APPROVED** [review]

**Pull request merged**
